[package]
name = "voidpoc"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.218", features = ["derive"] }
